### ISSUE TITLE
Create contribution guidelines

### ISSUE THREAD

**Issue by TheDormouse** [Wookey-Technologies/magna-carta#4]
Contribution guidelines should be created that shows proper formatting guidelines, acceptance criteria, and where to discuss changes. 

The discussion board could also be turned on to allow people propose new ideas without needing to submit the final result.

**Comment by 3MUl0R** [comment]
I second this

**Comment by onexdata** [comment]
This is a great idea. Thanks for taking care of this @3MUl0R! 👍
